services:
  auction-svc:
    image: auction-svc:latest
    hostname: auction-svc01
    build:
      context: ../auctionServiceAPI
      dockerfile: Dockerfile
    environment:
      - AuctionImagePath=/srv/resources/images
      - MongoConnectionString=mongodb://root:rootpassword@mongodb:27017/?authSource=admin
      - AuctionDatabase=auctions
      - AuctionCollection=list
      - GatewayUrl=http://gateway:4000
      - ImagePath=/srv/resources/images
    expose:
      - "8080"
    depends_on:
      - mongodb
    volumes:
      - auction-images-volume:/srv/resources/images
    networks:
      - auctionnet

  effect-svc:
    image: effect-svc:latest
    hostname: effect-svc01
    build:
      context: ../../effect-service/effectServiceAPI
      dockerfile: Dockerfile
    environment:
      - EffectImagePath=/srv/resources/effect-images
      - MongoConnectionString=mongodb://root:rootpassword@mongodb:27017/?authSource=admin
      - EffectDatabase=effects
      - EffectCollection=list
      - GatewayUrl=http://gateway:4000
      - ImagePath=/srv/resources/effect-images
    expose:
      - "8080"
    depends_on:
      - mongodb
    volumes:
      - effect-images-volume:/srv/resources/effect-images
    networks:
      - auctionnet

  nginx:
    image: nginx:latest
    container_name: "gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/srv/www/data
    depends_on:
      - auction-svc
      - effect-svc
    ports:
      - "4000:4000"
    networks:
      - auctionnet

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - auctionnet

networks:
  auctionnet:
    driver: bridge

volumes:
  mongodb_data_container:
  auction-images-volume:
    external: false
  effect-images-volume:
    external: false