services:
  auction-svc:
    image: auction-svc:latest
    hostname: auction-svc01
    build:
      context: ../auctionServiceAPI
      dockerfile: Dockerfile
    environment:
      - AuctionImagePath=/srv/resources/images
      - MongoConnectionString=mongodb://root:rootpassword@mongodb:27017/?authSource=admin
      - AuctionDatabase=auctions
      - AuctionCollection=list
      - GatewayUrl=http://gateway:4000
      - ImagePath=/srv/resources/images
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    expose:
      - "8080"
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - auction-images-volume:/srv/resources/images
    networks:
      - auctionnet

  effect-svc:
    image: effect-svc:latest
    hostname: effect-svc01
    build:
      context: ../../effect-service/effectServiceAPI
      dockerfile: Dockerfile
    environment:
      - EffectImagePath=/srv/resources/effect-images
      - MongoConnectionString=mongodb://root:rootpassword@mongodb:27017/?authSource=admin
      - EffectDatabase=effects
      - EffectCollection=list
      - GatewayUrl=http://gateway:4000
      - ImagePath=/srv/resources/effect-images
    expose:
      - "8080"
    depends_on:
      - mongodb
    volumes:
      - effect-images-volume:/srv/resources/effect-images
    networks:
      - auctionnet
    
  bidding-svc:
    build:
      context: ../../BiddingService/biddingServiceAPI
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq  
    networks:
      - auctionnet

  nginx:
    image: nginx:latest
    container_name: "gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/srv/www/data
    depends_on:
      - auction-svc
      - effect-svc
    ports:
      - "4000:4000"
    networks:
      - auctionnet

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - auctionnet
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (backend)
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - auctionnet
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auctionnet

networks:
  auctionnet:
    driver: bridge

volumes:
  mongodb_data_container:
  auction-images-volume:
    external: false
  effect-images-volume:
    external: false