name: CI - Docker Compose with Cloned Repos

on:
  push:
    branches: [ main ]

jobs:
  docker-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone DockerCommon repo
        run: git clone https://github.com/DeGamleGronOgOlsen/DockerCommon

      - name: Clone DockerBackendServices repo
        run: git clone https://github.com/DeGamleGronOgOlsen/DockerBackendServices.git

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker containers
        run: |
          docker compose -f DockerCommon/docker-compose.yml -f DockerBackendServices/docker-compose.yml up -d
