name: Automated API tests using Postman CLI

on:
  push:
    branches:
      - main
      - master

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Postman Collection with baseUrl
        run: postman collection run 42971438-d3a33369-52e1-4750-abe9-cf1bee22bfe4 --env-var baseUrl=http://localhost:4000/api
